apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-production
spec:
  acme:
    email: subash.chaudhary@globalyhub.com
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-key-cluster-issuer
    solvers:
    - http01:
        ingress:
          class: nginx
